# Site settings
name: Jimena Medina Rubio
title: Jimena Medina Rubio | PhD Candidate in Physical Oceanography
description: description
url: https://jimena-medinarubio.github.io/
baseurl: ''
email: j.medinarubio@uu.nl
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/me.png
resume: [cv]
social:
  - title: email
    url: mailto:j.medinarubio@uu.nl
  - title: github
    url: https://github.com/jimena-medinarubio
  - title: linkedin
    url: https://www.linkedin.com/in/jimena-medina-rubio/

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
